name: {{cookiecutter.conversion_name}}_env
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python==3.9
- ipython
- pip
- git
- pip:
  - -r {{cookiecutter.conversion_name}}_requirements.txt
  - -e .
